"""create document_chunks table

Revision ID: 3a900a15443a
Revises: cf04f880e71a
Create Date: 2026-09-16 00:39:03.218228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a900a15443a'
down_revision: Union[str, Sequence[str], None] = 'cf04f880e71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('subtopic_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'chunk_index', name='uq_chunks_material_index')
    )
    op.create_index(op.f('ix_document_chunks_concept_id'), 'document_chunks', ['concept_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_material_id'), 'document_chunks', ['material_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_project_id'), 'document_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_subtopic_id'), 'document_chunks', ['subtopic_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_topic_id'), 'document_chunks', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_topic_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_subtopic_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_project_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_material_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_concept_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
