"""add extraction fields to materials

Revision ID: 3c13e851f931
Revises: 708b62706a6e
Create Date: 2026-09-15 23:27:37.599974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c13e851f931'
down_revision: Union[str, Sequence[str], None] = '708b62706a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('materials', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('materials', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'error_message')
    op.drop_column('materials', 'page_count')
    op.drop_column('materials', 'extracted_text')
    # ### end Alembic commands ###
