"""create topics subtopics concepts tables

Revision ID: cf04f880e71a
Revises: 3c13e851f931
Create Date: 2026-09-15 23:59:11.578953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf04f880e71a'
down_revision: Union[str, Sequence[str], None] = '3c13e851f931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'title', name='uq_topics_project_title')
    )
    op.create_index(op.f('ix_topics_project_id'), 'topics', ['project_id'], unique=False)
    op.create_table('subtopics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'title', name='uq_subtopics_topic_title')
    )
    op.create_index(op.f('ix_subtopics_project_id'), 'subtopics', ['project_id'], unique=False)
    op.create_index(op.f('ix_subtopics_topic_id'), 'subtopics', ['topic_id'], unique=False)
    op.create_table('concepts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('subtopic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtopic_id', 'title', name='uq_concepts_subtopic_title')
    )
    op.create_index(op.f('ix_concepts_project_id'), 'concepts', ['project_id'], unique=False)
    op.create_index(op.f('ix_concepts_subtopic_id'), 'concepts', ['subtopic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepts_subtopic_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_project_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_subtopics_topic_id'), table_name='subtopics')
    op.drop_index(op.f('ix_subtopics_project_id'), table_name='subtopics')
    op.drop_table('subtopics')
    op.drop_index(op.f('ix_topics_project_id'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
