"""add unique attempt-question on quiz answers

Revision ID: d323053b3a54
Revises: 4b3487d354d6
Create Date: 2026-09-16 09:34:59.622317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd323053b3a54'
down_revision: Union[str, Sequence[str], None] = '4b3487d354d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_quiz_answers_attempt_question', 'quiz_answers', ['attempt_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quiz_answers_attempt_question', 'quiz_answers', type_='unique')
    # ### end Alembic commands ###
